### ISSUE TITLE
'no data' with coupling analysis

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#30]
Hi!
When I run sum of coupling or developer coupling with the latest version, the reports show "There is no data available for this diagram."
Is this just me?

**Comment by smontanari** [comment]
Are you running the analysis over an old time period? If that's the case it could be that some files referred to by github commits no longer exist in the latest version of the code repo, and those files maybe happened to be part of coupling relationships. I'll run some further tests to make sure no bug was introduced. As a sanity check also make sure the log files generated by code-forensics (in the tmp folder) do actually contain commit data

**Comment by jdevoo** [comment]
I am but I see some files have a few entries in the `vcslog_normalised_*` files under tmp

`developer-coupling-analysis --dateFrom=2016-01-01 --dateTo=2018-04-01` on Teevity ICE
https://github.com/Teevity/ice

I want to say I had some data before but usually these issues are my fault :-)

**Comment by iegik** [comment]
I've got following error
```
data_proxy.js:18 Unhandled rejection TypeError: Cannot read property 'tagName' of null
    at getSVGNode (http://localhost:3000/lib/d3-tip/index.js:248:13)
    at tip (http://localhost:3000/lib/d3-tip/index.js:33:13)
    at ut.call (http://localhost:3000/lib/d3/dist/d3.min.js:2:105857)
    at new module.exports (http://localhost:3000/js/d3_chart_components/d3_tooltip.js:20:13)
    at eval (http://localhost:3000/js/d3_chart_components/d3_data.js:28:7)
    at arrayEach (http://localhost:3000/lib/lodash/lodash.js:516:11)
    at Function.forEach (http://localhost:3000/lib/lodash/lodash.js:9342:14)
    at new D3Data (http://localhost:3000/js/d3_chart_components/d3_data.js:25:5)
    at new module.exports (http://localhost:3000/js/d3_chart_components/d3_component.js:23:16)
    at eval (http://localhost:3000/js/d3_chart_components/d3_chart.js:30:12)
    at arrayMap (http://localhost:3000/lib/lodash/lodash.js:639:23)
    at Function.map (http://localhost:3000/lib/lodash/lodash.js:9554:14)
    at new module.exports (http://localhost:3000/js/d3_chart_components/d3_chart.js:29:22)
    at eval (http://localhost:3000/js/diagrams/graph_painter.js:15:14)
    at arrayMap (http://localhost:3000/lib/lodash/lodash.js:639:23)
    at Function.map (http://localhost:3000/lib/lodash/lodash.js:9554:14)
```

**Comment by iegik** [comment]
Update d3-tip ?

**Comment by jdevoo** [comment]
I will close this because my original question was a user error. Widening the time-frame produced all outputs. @iegik I will let you create a separate issue; hope that's OK with you.
