### ISSUE TITLE
commit-message-analysis: Cannot read property 'isSelected' of undefined

### ISSUE THREAD

**Issue by iegik** [smontanari/code-forensics#33]
```
Unhandled rejection TypeError: Cannot read property 'isSelected' of undefined
    at eval (http://localhost:3000/js/controllers/report_controller.js:21:26)
    at r (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:31:9367)
    at i._settlePromiseFromHandler (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:14566)
    at i._settlePromise (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:15369)
    at i._settlePromise0 (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:16070)
    at i._settlePromises (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:17400)
    at i._fulfill (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:16441)
    at a._resolve (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:20879)
    at a._promiseFulfilled (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:21227)
    at i._settlePromise (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:15471)
    at i._settlePromise0 (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:16070)
    at i._settlePromises (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:17400)
    at i._fulfill (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:16441)
    at i._resolveCallback (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:13302)
    at i._settlePromiseFromHandler (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:14721)
    at i._settlePromise (http://localhost:3000/lib/bluebird/js/browser/bluebird.min.js:30:15369)
```

**Comment by smontanari** [comment]
This is a weird error, the reason it may be happening is when none of the graphs you are trying to visualise is successfully initialised. Which means that you have a bigger problem somewhere else, most likely the data that should initialise the graph is wrong or missing.

We can implement a fix that at least displays a more meaningful message, but it won't get you much further until we understand why the graphs fail to load the data

**Comment by iegik** [comment]
@smontanari Sorry, I have trouble to launch the code-forensics on project.

**Comment by smontanari** [comment]
I would suggest to take some time to read through the wiki and understand how to install configure code-forensics to run on your repo. If you still have problems please open an issue describing with as much detail as possible what is not working. In the meantime I'm closing this issue and opening one for the better error message
