### ISSUE TITLE
Can't find repository root

### ISSUE THREAD

**Issue by mhenrichsen** [smontanari/code-forensics#4]
Hi @smontanari, 

I'm having an issue where gulp can't seem to find the repository root directory.

`Madss-MacBook-Pro:cf madsgadehenrichsen$ gulp list-analysis-tasks
[09:04:34] Repository root directory does not exist: /desktop/betaflight

/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/index.js:32
    throw e;
    ^
Error: Repository root directory does not exist: /desktop/betaflight
    at CFValidationError (/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/models/validation_error.js:9:17)
    at validateConfig (/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/models/repository.js:21:11)
    at new module.exports (/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/models/repository.js:27:3)
    at new module.exports (/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/runtime/task_context.js:31:21)
    at Object.module.exports.configure (/Users/madsgadehenrichsen/Desktop/CF/node_modules/code-forensics/lib/index.js:21:19)
    at Object.<anonymous> (/Users/madsgadehenrichsen/Desktop/CF/gulpfile.js:1:89)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

The folder "betaflight" located on desktop. Am I doing this wrong?

**Comment by mhenrichsen** [comment]
Made it work. Had to include the whole path and not just for my user.
