### ISSUE TITLE
Help me with MacOS running

### ISSUE THREAD

**Issue by KirillVolkov** [smontanari/code-forensics#42]
`~/Documents/forensics $ gulp
[15:34:00] Requiring external module @babel/register
/Users/kirillvolkov/Documents/forensics/node_modules/code-forensics/lib/index.js:31
    if (e instanceof CFValidationError) { logger.error(e.message); }
                                                 ^

TypeError: Cannot read property 'error' of undefined
    at Object.module.exports.configure (/Users/kirillvolkov/Documents/forensics/node_modules/code-forensics/lib/index.js:31:50)
    at Object.configure (/Users/kirillvolkov/Documents/forensics/gulpfile.babel.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/Users/kirillvolkov/Documents/forensics/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/Users/kirillvolkov/Documents/forensics/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:201:12)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:191:5)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:149:9`

**Comment by smontanari** [comment]
Sorry for the late response @KirillVolkov. I've been flat out busy the past month and didn't have time to look into this. I think this is a silly bug and I should be able to fix it shortly

**Comment by smontanari** [comment]
version 2.2.1 should have fixed the logging problem. Feel free to open another issue if you still have troubles running code-forensics. And thank you for raising the issue in the first place
